all:
	#gcc initShell.c -o initShell.out -w
	gcc main.c -o shell.out -lreadline -w
	gcc ls.c -o ls.out -w
	gcc pwd.c -o pwd.out -w
	gcc help.c -o help.out -w
	gcc clear.c -o clear.out -w
	gcc pipe.c -o pipe.out -w
	gcc cat.c -o cat.out -w
	gcc rm.c -o rm.out -w
	gcc EXECUTE.c -o EXE.out -w
	gcc pstree.c -o pstree.out -w
	gcc create.c -o create.out -w
	gcc redir.c -o redir.out -w
	gcc cp.c -o cp.out -w
	gcc man.c -o man.out -w